# Generated by Django 2.1 on 2018-08-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrics',
            old_name='crawler_name',
            new_name='crawlerName',
        ),
    ]
