# Generated by Django 2.1 on 2018-08-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_resultpage_companylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPageX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyLogo', models.ImageField(default='img/sample.jpeg', upload_to='./static/pic_folder/')),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultpagex', to='dashboard.Crawler')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='img/sample.jpeg', upload_to='./static/pic_folder/'),
        ),
        migrations.AlterField(
            model_name='resultpage',
            name='companyLogo',
            field=models.ImageField(default='img/sample.jpeg', upload_to='./static/pic_folder/'),
        ),
    ]
