# Generated by Django 2.1 on 2018-08-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultPageX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websitename', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=50)),
                ('companyLogo', models.ImageField(default='img/sample.jpeg', upload_to='./static/pic_folder/')),
                ('headerTemplate', models.CharField(max_length=50)),
                ('bodyTemplate', models.CharField(max_length=50)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultpagex', to='dashboardfinal.Crawler')),
            ],
        ),
    ]
