# Generated by Django 2.1 on 2018-08-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardfinal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultpagex',
            name='numberOfResults',
            field=models.IntegerField(default=5),
        ),
    ]
