# Generated by Django 2.1 on 2018-08-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardfinal', '0002_resultpagex_numberofresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultpagex',
            name='bodyTemplate',
        ),
    ]
